"use client";

import React, { createContext, useContext, useState, useEffect } from 'react';

export type Language = 'en' | 'pidgin' | 'yo' | 'ig' | 'ha';

export interface LanguageOption {
  code: Language;
  label: string;
  shortLabel: string;
}

export const LANGUAGE_OPTIONS: LanguageOption[] = [
  { code: 'en', label: 'English', shortLabel: 'ENG' },
  { code: 'pidgin', label: 'Naija Pidgin', shortLabel: 'PIDGIN' },
  { code: 'yo', label: 'Yorùbá', shortLabel: 'YORÙBÁ' },
  { code: 'ig', label: 'Igbo', shortLabel: 'IGBO' },
  { code: 'ha', label: 'Hausa', shortLabel: 'HAUSA' },
];

interface LanguageContextType {
  lang: Language;
  setLanguage: (lang: Language) => void;
  toggleLanguage: () => void;
  t: (key: string) => string;
  languages: LanguageOption[];
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    heroTitle: "Lagos Real Estate, Redefined.",
    heroSubtitle: "Curated residential & commercial spaces across Nigeria.",
    exploreBtn: "Explore Collection",
    searchPlaceholder: "Search city, state, or property...",
    allProperties: "All Properties",
    residential: "Houses & Apartments",
    commercial: "Shops & Commercial",
    verified: "Verified",
    perYear: "yr",
    perMonth: "mo",
    perWeek: "wk",
    perDay: "day",
    contactAgent: "Contact Agent",
    chatWhatsapp: "Chat on WhatsApp",
    callAgent: "Call Agent",
    compare: "Compare",
    save: "Save",
    saved: "Saved",
    agentPortal: "Agent Portal",
    tenantPortal: "Tenant Dashboard",
    testimonialsTitle: "What People Say",
    agentHeroTitle: "List your portfolio.",
    agentHeroSubtitle: "Close deals faster.",
    agentHeroDesc: "Join Nigeria's most exclusive real estate network. Connect directly with high-budget tenants and buyers across Lagos, Abuja, and Port Harcourt.",
    claimFreeMonth: "Claim Free Month",
    viewPricing: "View Pricing & 5% Cut",
    beginJourney: "Begin your journey to exceptional real estate.",
    locationLbl: "Location",
    propTypeLbl: "Property Type",
    plotsOfLand: "Plots of Land",
    discoverBtn: "Discover",
    trustedBy: "Trusted by Buyers, Tenants & Top Agents",
    readyToAcquire: "Ready to acquire your next crib?",
    enterCollection: "Enter The Collection",
    promoUnlocked: "PROMO UNLOCKED",
    agentTermsLbl: "Agent Terms",
    firstMonthSub: "First Month Subscription",
    firstMonthDesc: "₦0 (100% FREE for your first 30 days)",
    monthlyMem: "Monthly Membership",
    monthlyMemDesc: "₦1,500 / month flat subscription after trial",
    naijaSpacesCom: "NaijaSpaces Commission",
    naijaSpacesComDesc: "We add a 5% platform fee on top of your asking price.",
    cancelAnytime: "Cancel or pause anytime from your dashboard.",
    whyTopAgents: "Why Top Agents Choose Us",
    builtExclusive: "Built Exclusively for Real Estate Pros",
    feat1Title: "Guaranteed Targeted Traffic",
    feat1Desc: "We run high-budget campaigns across Google & Meta to drive qualified, high-net-worth tenants directly to your listings.",
    feat2Title: "Verified Agent Badge",
    feat2Desc: "Instantly build client trust. Verified partner agents get 4x more direct inquiries and zero time-wasting interactions.",
    feat3Title: "Direct WhatsApp Leads",
    feat3Desc: "No middlemen or delayed forwards. Interested buyers click once to start a direct WhatsApp chat or phone call with you.",
    feat4Title: "Agent Command Center",
    feat4Desc: "Upload HD galleries, set custom lease terms, and easily manage your payout bank account.",
    seamlessOnboard: "Seamless Onboarding",
    howItWorks: "How It Works in 3 Simple Steps",
    step1Title: "Create Free Agent Account",
    step1Desc: "Sign up in under 60 seconds with your email and WhatsApp contact number. Your 1st month subscription fee is 100% waived.",
    step2Title: "Upload Properties & Set Price",
    step2Desc: "Input your net asking price. Our platform automatically adds our 5% commission on top so buyers pay the total price transparently.",
    step3Title: "Receive Direct Leads & Payments",
    step3Desc: "Get direct WhatsApp inquiries or automated Paystack bank payouts sent straight to your verified Nigerian bank account.",
    transPricing: "Transparent Pricing",
    zeroHidden: "Zero Hidden Charges",
    promoOffer: "PROMO OFFER",
    firstMonthTrial: "1st Month Trial",
    for30days: "for 30 days",
    startFreeMonth: "Start Free Month Now",
    standardPlan: "STANDARD PLAN",
    perMonthTxt: "/ month",
    regAsAgent: "Register as Agent",
    agentFaq: "Agent FAQ",
    faqTitle: "Frequently Asked Questions",
    faq1Q: "How does the 5% platform cut work with my asking price?",
    faq1A: "When you list a property for ₦2,000,000, our system adds our 5% platform commission on top (₦100,000). The total price displayed to the buyer on checkout is ₦2,100,000. You receive 100% of your asking price directly into your bank account!",
    faq2Q: "How do I receive my 1st Month Free?",
    faq2A: "Simply click 'Claim Free Month' and complete your agent registration. You do not need a credit card. Your listing privileges activate immediately for 30 days.",
    faq3Q: "Can I list short-lets, rentals, and outright sales?",
    faq3A: "Yes! NaijaSpaces supports daily/monthly short-let stays, yearly residential rentals, commercial leases, and outright land/building sales.",
    joinAgentsTitle: "Join 500+ Verified Nigerian Agents",
    joinAgentsDesc: "Start listing your property portfolio today with your 1st month 100% free.",
    getStartedFree: "Get Started Free →"
  },
  pidgin: {
    heroTitle: "Fine Houses for Naija, Simplified.",
    heroSubtitle: "Correct apartment, house, and shop space for Lagos & across Naija.",
    exploreBtn: "Look the Cribs",
    searchPlaceholder: "Find city, state, or house...",
    allProperties: "All Cribs",
    residential: "House & Flat",
    commercial: "Shop & Office",
    verified: "Original",
    perYear: "yr",
    perMonth: "mo",
    perWeek: "wk",
    perDay: "day",
    contactAgent: "Talk to Agent",
    chatWhatsapp: "WhatsApp the Agent",
    callAgent: "Call Agent Now",
    compare: "Compare Am",
    save: "Save Am",
    saved: "Saved",
    agentPortal: "Agent Portal",
    tenantPortal: "Tenant Dashboard",
    testimonialsTitle: "Wetin People Talk",
    agentHeroTitle: "Post your houses.",
    agentHeroSubtitle: "Sell dem sharp sharp.",
    agentHeroDesc: "Join the biggest agent network for Naija. Connect direct with people wey get money for Lagos, Abuja, and Port Harcourt.",
    claimFreeMonth: "Collect Awoof Month",
    viewPricing: "See Pricing & 5% Cut",
    beginJourney: "Start your journey for better house.",
    locationLbl: "Location",
    propTypeLbl: "House Type",
    plotsOfLand: "Empty Land",
    discoverBtn: "Find Am",
    trustedBy: "Trusted by Buyers, Tenants & Top Agents",
    readyToAcquire: "You don ready to get your next crib?",
    enterCollection: "Enter The Collection",
    promoUnlocked: "AWOOF UNLOCKED",
    agentTermsLbl: "Agent Terms",
    firstMonthSub: "First Month Subscription",
    firstMonthDesc: "₦0 (100% Awoof for your first 30 days)",
    monthlyMem: "Monthly Membership",
    monthlyMemDesc: "₦1,500 / month flat subscription after trial",
    naijaSpacesCom: "NaijaSpaces Commission",
    naijaSpacesComDesc: "We go add 5% platform fee on top your asking price.",
    cancelAnytime: "Cancel or pause anytime from your dashboard.",
    whyTopAgents: "Why Top Agents Choose Us",
    builtExclusive: "Built Exclusively for Real Estate Pros",
    feat1Title: "Sure Traffic for your adverts",
    feat1Desc: "We run big campaigns across Google & Meta to bring buyers straight to your houses.",
    feat2Title: "Original Agent Badge",
    feat2Desc: "Make clients trust you fast. Verified agents get 4x more direct chats.",
    feat3Title: "Direct WhatsApp Chats",
    feat3Desc: "No middlemen. Buyers click once to start WhatsApp chat or call you straight.",
    feat4Title: "Agent Command Center",
    feat4Desc: "Upload sharp pictures, set your lease terms, and arrange your bank account for payment.",
    seamlessOnboard: "Easy Setup",
    howItWorks: "How It Works in 3 Simple Steps",
    step1Title: "Open Free Agent Account",
    step1Desc: "Sign up sharp sharp with your email and WhatsApp number. First month na awoof.",
    step2Title: "Post Houses & Set Price",
    step2Desc: "Put your net asking price. Our platform go automatically add our 5% commission on top so buyers pay everything transparently.",
    step3Title: "Collect Direct Chats & Money",
    step3Desc: "Get direct WhatsApp chats or Paystack bank payouts sent straight to your Nigerian bank account.",
    transPricing: "Clear Pricing",
    zeroHidden: "No Hidden Charges",
    promoOffer: "AWOOF OFFER",
    firstMonthTrial: "1st Month Trial",
    for30days: "for 30 days",
    startFreeMonth: "Start Awoof Month Now",
    standardPlan: "NORMAL PLAN",
    perMonthTxt: "/ month",
    regAsAgent: "Register as Agent",
    agentFaq: "Agent FAQ",
    faqTitle: "Questions People Dey Ask",
    faq1Q: "How the 5% platform cut dey work with my asking price?",
    faq1A: "When you list property for ₦2,000,000, our system go add our 5% commission on top (₦100,000). Total price for buyer na ₦2,100,000. You go receive your full ₦2,000,000 straight to your bank!",
    faq2Q: "How I go receive my 1st Month Awoof?",
    faq2A: "Just click 'Claim Free Month' and complete your registration. You no need card. Your listing go start immediately for 30 days.",
    faq3Q: "I fit list short-lets, rentals, and outright sales?",
    faq3A: "Yes! NaijaSpaces support daily/monthly short-let, yearly rent, commercial lease, and outright land/building sales.",
    joinAgentsTitle: "Join 500+ Verified Naija Agents",
    joinAgentsDesc: "Start listing your properties today with your 1st month 100% free.",
    getStartedFree: "Start Now For Free →"
  },
  yo: {
    heroTitle: "Awọn Ilé Aláradagba Ní Nàìjíríà.",
    heroSubtitle: "Awọn ilé àgbàru, ilé gbígbé, ati ilé iṣẹ́ gíga ní Èkó ati gbogbo Nàìjíríà.",
    exploreBtn: "Wo Awọn Ilé Aláradagba",
    searchPlaceholder: "Wá ìlú, ìpínlẹ̀, tabi ilé...",
    allProperties: "Gbogbo Awọn Ilé",
    residential: "Ilé Gbígbé ati Àbáwọlé",
    commercial: "Ilé Iṣẹ́ ati Ṣọ́ọ̀pù",
    verified: "Ti A Fowósí",
    perYear: "ọdún",
    perMonth: "osù",
    perWeek: "ọ̀ṣẹ̀",
    perDay: "ọjọ́",
    contactAgent: "Sọ̀rọ̀ Pẹ̀lú Agbeṣẹ́",
    chatWhatsapp: "Fi Ṣátì Ránsẹ́ lórí WhatsApp",
    callAgent: "Pè Agbeṣẹ́ Sí Ọ̀rọ̀",
    compare: "Fi We Ra Wọn",
    save: "Fomọ́lẹ̀",
    saved: "Ti A Fomọ́lẹ̀",
    agentPortal: "Kọmputa Agbeṣẹ́",
    tenantPortal: "Kọmputa Alábàáwọlé",
    testimonialsTitle: "Erò Awọn Oníbàárà",
    agentHeroTitle: "Fi awọn ilé rẹ sori ayelujara.",
    agentHeroSubtitle: "Ta wọn ni kope kope.",
    agentHeroDesc: "Darapọ mọ ẹgbẹ awọn aṣoju ile ti o tobi julọ ni Naijiria. Sopọ pẹlu awọn ti o ni owo ni Eko, Abuja, ati Port Harcourt.",
    claimFreeMonth: "Gba Osu Kan Ọfẹ",
    viewPricing: "Wo Iye Owo & 5%",
    beginJourney: "Bẹrẹ irin-ajo rẹ si ohun-ini gidi to dara.",
    locationLbl: "Ipo",
    propTypeLbl: "Iru Ohun-ini",
    plotsOfLand: "Ilẹ",
    discoverBtn: "Ṣawari",
    trustedBy: "Awọn Olura ati Awọn Agbeṣẹ́ Gbekele Wa",
    readyToAcquire: "Ṣe o ti ṣetan lati gba ile rẹ?",
    enterCollection: "Wọle si Akojọpọ Ile",
    promoUnlocked: "EBU ỌFẸ TI ṢI",
    agentTermsLbl: "Awọn Ofin Aṣoju",
    firstMonthSub: "Osu Akọkọ",
    firstMonthDesc: "₦0 (100% ỌFẸ fun ọjọ 30 akọkọ rẹ)",
    monthlyMem: "Owo Oṣooṣu",
    monthlyMemDesc: "₦1,500 / oṣu kan lẹhin ọfẹ",
    naijaSpacesCom: "Igbimọ NaijaSpaces",
    naijaSpacesComDesc: "A fi 5% kun idiyele rẹ.",
    cancelAnytime: "O le fagile nigbakugba.",
    whyTopAgents: "Idi Ti Awọn Aṣoju Ṣe N Yan Wa",
    builtExclusive: "A Kọ Fun Awọn Ọjọgbọn",
    feat1Title: "Ipolowo Ati Onibara To Daju",
    feat1Desc: "A n ṣiṣẹ ipolowo lori Google & Meta lati mu awọn onibara ọlọrọ wa si ile rẹ.",
    feat2Title: "Baaji Aṣoju Ti A Fowosi",
    feat2Desc: "Kọ igbẹkẹle alabara. Awọn aṣoju n gba ipe diẹ sii.",
    feat3Title: "WhatsApp Taara",
    feat3Desc: "Ko si alarina. Awọn olura n tẹ lẹẹkan lati ba ọ sọrọ ni WhatsApp.",
    feat4Title: "Aaye Iṣakoso Aṣoju",
    feat4Desc: "Fi awọn aworan ile sori ayelujara ati ṣeto akọọlẹ banki rẹ.",
    seamlessOnboard: "Iforukọsilẹ Irọrun",
    howItWorks: "Bii O Ṣe N Ṣiṣẹ Ni Awọn Igbesẹ 3",
    step1Title: "Ṣẹda Akọọlẹ Aṣoju Ọfẹ",
    step1Desc: "Forukọsilẹ ni iṣẹju kan pẹlu imeeli rẹ. Osu akọkọ jẹ ọfẹ.",
    step2Title: "Fi Awọn Ile Sori Ayelujara & Iye Owo",
    step2Desc: "Fi iye owo rẹ sii. Eto wa yoo fi 5% kun fun awọn ti on ra ile.",
    step3Title: "Gba Awọn Onibara & Owo Taara",
    step3Desc: "Gba ifiranṣẹ WhatsApp tabi owo taara sinu akọọlẹ banki rẹ ni Naijiria.",
    transPricing: "Iye Owo Ti O Daju",
    zeroHidden: "Ko Si Owo Farasin",
    promoOffer: "EBU ỌFẸ",
    firstMonthTrial: "Idanwo Oṣu Akọkọ",
    for30days: "fun ọjọ 30",
    startFreeMonth: "Bẹrẹ Oṣu Ọfẹ Rẹ Bayi",
    standardPlan: "ETO DEEDE",
    perMonthTxt: "/ osù",
    regAsAgent: "Forukọsilẹ Bi Aṣoju",
    agentFaq: "FAQ Aṣoju",
    faqTitle: "Awọn Ibeere Nigbagbogbo",
    faq1Q: "Bawo ni 5% ṣe n ṣiṣẹ pẹlu iye owo mi?",
    faq1A: "Nigbati o ba ta ile fun ₦2,000,000, eto wa yoo fi 5% kun (₦100,000). Owo lapapọ ti ẹniti on ra ile yoo ri jẹ ₦2,100,000. Iwọ yoo gba ₦2,000,000 rẹ taara sinu banki rẹ!",
    faq2Q: "Bawo ni mo ṣe le gba Oṣu Akọkọ Ọfẹ mi?",
    faq2A: "Tẹ 'Gba Osu Kan Ọfẹ' ati pari iforukọsilẹ rẹ. O ko nilo kaadi banki.",
    faq3Q: "Ṣe MO le fi ile kukuru, iyalo, ati tita patapata sori ayelujara?",
    faq3A: "Bẹẹni! NaijaSpaces gba iyalo ojoojumọ, ọdọọdun, ile itaja, ati tita ilẹ patapata.",
    joinAgentsTitle: "Darapọ Mọ Awọn Aṣoju Nàìjíríà 500+",
    joinAgentsDesc: "Bẹrẹ fifi ile rẹ sori ayelujara loni pẹlu oṣu akọkọ ọfẹ.",
    getStartedFree: "Bẹrẹ Ni Ọfẹ →"
  },
  ig: {
    heroTitle: "Ụlọ Obibi na azụmahịa kachasị mma na Naịjirịa.",
    heroSubtitle: "Kọntaktị ụlọ obibi na ụlọ azụmahịa kachasị mma na Lagos na Nigeria niile.",
    exploreBtn: "Nyochaa Ụlọ Niile",
    searchPlaceholder: "Chọọ obodo, steeti, ma ọ bụ ụlọ...",
    allProperties: "Ụlọ Niile",
    residential: "Ụlọ Obibi na Fụlátị",
    commercial: "Ụlọ Azụmahịa na Shọpụ",
    verified: "A Nyochaala",
    perYear: "afọ",
    perMonth: "ọnwa",
    perWeek: "izu",
    perDay: "ụbọchị",
    contactAgent: "Kpọtụrụ Agent",
    chatWhatsapp: "Ziga Ozi na WhatsApp",
    callAgent: "Kpọọ Agent Oku",
    compare: "Yiri Ha N'aka",
    save: "Kedo Ya",
    saved: "Kedoela",
    agentPortal: "Pọtụlụ Agent",
    tenantPortal: "Pọtụlụ Onye Rente",
    testimonialsTitle: "Ihe Ndị Mmadụ Na-ekwu",
    agentHeroTitle: "Debe ụlọ gị na ịntanetị.",
    agentHeroSubtitle: "Ree ha ngwa ngwa.",
    agentHeroDesc: "Soro netwọkụ ndị ọrụ ụlọ kacha ukwuu na Naịjirịa. Jikọọ na ndị nwere ego na Lagos, Abuja, na Port Harcourt.",
    claimFreeMonth: "Nata Otu Ọnwa N'efu",
    viewPricing: "Hụ Ọnụahịa & 5%",
    beginJourney: "Bido njem gị maka ụlọ kacha mma.",
    locationLbl: "Ebe",
    propTypeLbl: "Ụdị Ụlọ",
    plotsOfLand: "Ala",
    discoverBtn: "Chọpụta",
    trustedBy: "Ndị Zụrụ, Ndị Rente na Ndị Ọrụ Ụlọ Tụkwasịrị Obi",
    readyToAcquire: "Ị dị njikere ịzụta ụlọ gị ọzọ?",
    enterCollection: "Banye Na Nchịkọta Ụlọ",
    promoUnlocked: "ONYINYE EMEGHELA",
    agentTermsLbl: "Iwu Ndị Ọrụ",
    firstMonthSub: "Ndebanye Aha Ọnwa Mbụ",
    firstMonthDesc: "₦0 (100% N'EFU maka ụbọchị 30 mbụ gị)",
    monthlyMem: "Ịbụ Onye Otu Ọnwa",
    monthlyMemDesc: "₦1,500 / ọnwa mgbe oge nnwale gasịrị",
    naijaSpacesCom: "Kọmishọna NaijaSpaces",
    naijaSpacesComDesc: "Anyị na-atụkwasị 5% n'elu ọnụahịa gị.",
    cancelAnytime: "Ị nwere ike ịkagbu ya mgbe ọ bụla.",
    whyTopAgents: "Ihe Mere Ndị Ọrụ Kacha Mma Ji Ahọrọ Anyị",
    builtExclusive: "Ewepụtara Maka Ndị Ọkachamara",
    feat1Title: "Mgbasa Ozi Na Ndị Ahịa A Ma Ama",
    feat1Desc: "Anyị na-eme mgbasa ozi na Google & Meta iji weta ndị ahịa bara ọgaranya n'ụlọ gị.",
    feat2Title: "Baji Onye Ọrụ A Nyochaala",
    feat2Desc: "Mee ka ndị ahịa tụkwasị gị obi. Ndị ọrụ na-enweta ọtụtụ oku kpọmkwem.",
    feat3Title: "WhatsApp Kpọmkwem",
    feat3Desc: "Enweghị ndị etiti. Ndị zụrụ na-apị otu ugboro ka ha na gị kpaa nkata na WhatsApp.",
    feat4Title: "Ebe Njikwa Onye Ọrụ",
    feat4Desc: "Tee foto ụlọ na ịntanetị wee hazie akaụntụ ụlọ akụ gị.",
    seamlessOnboard: "Ndebanye Aha Dị Mfe",
    howItWorks: "Otu Ọ Si Arụ Ọrụ Na Usoro 3",
    step1Title: "Mepụta Akaụntụ Onye Ọrụ N'efu",
    step1Desc: "Debanye aha n'ime otu nkeji site na email gị. Ọnwa mbụ bụ n'efu.",
    step2Title: "Debe Ụlọ na Ịntanetị & Ọnụahịa",
    step2Desc: "Tinye ọnụahịa gị. Usoro anyị ga-atụkwasị 5% maka ndị zụrụ ụlọ.",
    step3Title: "Nweta Ndị Ahịa & Ego Kpọmkwem",
    step3Desc: "Nweta ozi WhatsApp ma ọ bụ ego kpọmkwem na akaụntụ ụlọ akụ gị na Naịjirịa.",
    transPricing: "Ọnụahịa Doro Anya",
    zeroHidden: "Enweghị Ego Ezoro Ezo",
    promoOffer: "ONYINYE N'EFU",
    firstMonthTrial: "Nnwale Ọnwa Mbụ",
    for30days: "maka ụbọchị 30",
    startFreeMonth: "Bido Ọnwa N'efu Gị Ugbu a",
    standardPlan: "ATỤMATỤ NKỊTỊ",
    perMonthTxt: "/ ọnwa",
    regAsAgent: "Debanye Aha Dị Ka Onye Ọrụ",
    agentFaq: "Ajụjụ Ndị Ọrụ",
    faqTitle: "Ajụjụ Ndị A Na-ajụkarị",
    faq1Q: "Kedu otu 5% si arụ ọrụ na ọnụahịa m?",
    faq1A: "Mgbe ị na-ere ụlọ maka ₦2,000,000, usoro anyị ga-atụkwasị 5% (₦100,000). Ngụkọta ego onye zụrụ ga-ahụ bụ ₦2,100,000. Ị ga-enweta ₦2,000,000 gị kpọmkwem n'ụlọ akụ gị!",
    faq2Q: "Kedu otu m ga-esi nweta Ọnwa Mbụ N'efu m?",
    faq2A: "Naanị pịa 'Nata Otu Ọnwa N'efu' ma mechaa ndebanye aha gị. Ị chọghị kaadị akụ.",
    faq3Q: "Enwere m ike idebe ụlọ nwa oge, ịgbazite, na ire ere kpamkpam?",
    faq3A: "Ee! NaijaSpaces na-akwado ụlọ kwa ụbọchị, kwa afọ, ụlọ ahịa, na ire ala/ụlọ kpamkpam.",
    joinAgentsTitle: "Soro Ndị Ọrụ Naịjirịa 500+",
    joinAgentsDesc: "Bido idenye ụlọ gị n'ịntanetị taa na ọnwa mbụ n'efu.",
    getStartedFree: "Bido N'efu →"
  },
  ha: {
    heroTitle: "Kayan Gida da Gidaje Mafi Inganci a Nijeriya.",
    heroSubtitle: "Tsarin gidajen zama da na kasuwanci a Legas da ko'ina a Nijeriya.",
    exploreBtn: "Duba Dukkan Gidaje",
    searchPlaceholder: "Nemi birni, jiha, ko gida...",
    allProperties: "Dukkan Gidaje",
    residential: "Gidajen Zama da Fula-Toci",
    commercial: "Gidajen Kasuwanci da Shaguna",
    verified: "Ingantacce",
    perYear: "shekara",
    perMonth: "wata",
    perWeek: "mako",
    perDay: "rana",
    contactAgent: "Tuntubi Dilali",
    chatWhatsapp: "Yi Magana a WhatsApp",
    callAgent: "Kira Dilali",
    compare: "Kwatanta Gidaje",
    save: "Ajiye",
    saved: "An Ajiye",
    agentPortal: "Manhajar Dilalai",
    tenantPortal: "Manhajar Masu Haya",
    testimonialsTitle: "Cewar Abokan Ciniki",
    agentHeroTitle: "Sa gidajen ka a yanar gizo.",
    agentHeroSubtitle: "Sayar da su da sauri.",
    agentHeroDesc: "Shiga babbar hanyar sadarwa ta dillalan gidaje a Najeriya. Haɗu da masu kudi a Legas, Abuja, da Fatakwal.",
    claimFreeMonth: "Karbi Wata Daya Kyauta",
    viewPricing: "Duba Farashi da 5%",
    beginJourney: "Fara tafiyar ka zuwa gida mai kyau.",
    locationLbl: "Wuri",
    propTypeLbl: "Irin Gida",
    plotsOfLand: "Fili",
    discoverBtn: "Gano",
    trustedBy: "Masu Siyayya da Dillalai Sun Yarda Da Mu",
    readyToAcquire: "Shin a shirye kake don samun gidanka na gaba?",
    enterCollection: "Shiga Cikin Gidaje",
    promoUnlocked: "KYAUTA TA BUDE",
    agentTermsLbl: "Sharuɗɗan Dillali",
    firstMonthSub: "Biyan Wata Na Farko",
    firstMonthDesc: "₦0 (100% KYAUTA don kwanaki 30 na farko)",
    monthlyMem: "Biyan Wata-wata",
    monthlyMemDesc: "₦1,500 / wata bayan gwajin",
    naijaSpacesCom: "Kwamitin NaijaSpaces",
    naijaSpacesComDesc: "Mun kara 5% a kan farashin ku.",
    cancelAnytime: "Kuna iya soke kowane lokaci.",
    whyTopAgents: "Me Yasa Manyan Dillalai Suke Zaben Mu",
    builtExclusive: "An Yi Musamman Don Kwararru",
    feat1Title: "Talla Da Abokan Ciniki Masu Kudi",
    feat1Desc: "Muna gudanar da tallace-tallace a Google & Meta don kawo masu kudi zuwa gidajen ku.",
    feat2Title: "Tambarin Dillali Ingantacce",
    feat2Desc: "Gina amincewar abokan ciniki. Dillalai suna samun ƙarin kira kai tsaye.",
    feat3Title: "WhatsApp Kai Tsaye",
    feat3Desc: "Babu 'yan tsakiya. Masu siyayya suna latsa sau ɗaya don yin magana a WhatsApp.",
    feat4Title: "Cibiyar Kula Da Dillali",
    feat4Desc: "Sa hotunan gidaje a yanar gizo kuma saita asusun bankin ku.",
    seamlessOnboard: "Rijista Mai Sauki",
    howItWorks: "Yadda Yake Aiki A Matakai 3",
    step1Title: "Bude Asusun Dillali Kyauta",
    step1Desc: "Yi rijista a cikin minti ɗaya da imel ɗin ku. Wata na farko kyauta ne.",
    step2Title: "Sa Gidaje A Yanar Gizo & Farashi",
    step2Desc: "Sa farashin ku. Tsarin mu zai kara 5% don masu siyayya.",
    step3Title: "Karbi Abokan Ciniki & Kudi Kai Tsaye",
    step3Desc: "Karbi saƙon WhatsApp ko kuɗi kai tsaye a asusun bankin ku na Najeriya.",
    transPricing: "Farashi Mai Sauki",
    zeroHidden: "Babu Boyayyun Caji",
    promoOffer: "TAYIN KYAUTA",
    firstMonthTrial: "Gwajin Wata Na Farko",
    for30days: "don kwanaki 30",
    startFreeMonth: "Fara Wata Kyauta Yanzu",
    standardPlan: "TSARI NA GARI",
    perMonthTxt: "/ wata",
    regAsAgent: "Yi Rijista A Matsayin Dillali",
    agentFaq: "Tambayoyin Dillalai",
    faqTitle: "Tambayoyi Da Ake Yawan Yi",
    faq1Q: "Ta yaya 5% ke aiki tare da farashi na?",
    faq1A: "Lokacin da kake sayar da gida akan ₦2,000,000, tsarin mu zai kara 5% (₦100,000). Jimlar kuɗin da mai siyayya zai gani shine ₦2,100,000. Za ku karɓi ₦2,000,000 naku kai tsaye a bankin ku!",
    faq2Q: "Ta yaya zan karɓi Wata Na Farko Kyauta?",
    faq2A: "Kawai danna 'Karbi Wata Daya Kyauta' kuma ku kammala rijistar ku. Ba ku buƙatar katin banki.",
    faq3Q: "Zan iya sa gidan haya na ɗan lokaci, na shekara, da sayarwa gaba ɗaya?",
    faq3A: "Eh! NaijaSpaces yana goyan bayan haya na yau da kullun, na shekara, shago, da sayar da fili/gida gaba ɗaya.",
    joinAgentsTitle: "Shiga Cikin Dillalai 500+ A Najeriya",
    joinAgentsDesc: "Fara sa gidajen ku a yanar gizo yau tare da wata na farko kyauta.",
    getStartedFree: "Fara Kyauta →"
  }
};

const LanguageContext = createContext<LanguageContextType>({
  lang: 'en',
  setLanguage: () => {},
  toggleLanguage: () => {},
  t: (key: string) => key,
  languages: LANGUAGE_OPTIONS,
});

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [lang, setLang] = useState<Language>('en');

  useEffect(() => {
    if (typeof window !== 'undefined') {
      const savedLang = localStorage.getItem('naijaspaces_lang') as Language;
      if (savedLang && translations[savedLang]) {
        setLang(savedLang);
      }
    }
  }, []);

  const handleSetLanguage = (newLang: Language) => {
    if (translations[newLang]) {
      setLang(newLang);
      if (typeof window !== 'undefined') {
        localStorage.setItem('naijaspaces_lang', newLang);
      }
    }
  };

  const toggleLanguage = () => {
    const codes: Language[] = ['en', 'pidgin', 'yo', 'ig', 'ha'];
    const currentIndex = codes.indexOf(lang);
    const nextLang = codes[(currentIndex + 1) % codes.length];
    handleSetLanguage(nextLang);
  };

  const t = (key: string) => {
    return translations[lang]?.[key] || translations['en'][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ lang, setLanguage: handleSetLanguage, toggleLanguage, t, languages: LANGUAGE_OPTIONS }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
